//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ExcelExporter
//     version 2.2
//     from https://github.com/xuzhuoxi/ExcelExporter
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package server

const (
	// CodeSuc 成功
	CodeSuc int32 = 0
	// CodeExtensionNotExist 扩展错误-扩展不存在
	CodeExtensionNotExist int32 = 1
	// CodeProtoNotExist 协议错误-协议不存在
	CodeProtoNotExist int32 = 2
	// CodeExtensionDisable 扩展禁用
	CodeExtensionDisable int32 = 3
	// CodeArgs 参数错误
	CodeArgs int32 = 4
	// CodeInternal 服务器内部错误
	CodeInternal int32 = 5
	// CodeDbQuery 数据库执行错误
	CodeDbQuery int32 = 6
	// CodeTimeout 请求超时
	CodeTimeout int32 = 7
	// CodeRight 权限不足
	CodeRight int32 = 8
	// CodeStatus 状态不匹配
	CodeStatus int32 = 9
	// CodeRepeat 请求重复
	CodeRepeat int32 = 10
	// CodeFreq 请求过于频繁
	CodeFreq int32 = 11
	// CodeOther 其它错误
	CodeOther int32 = 12
)
