//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ExcelExporter
//     version 2.0
//     from https://github.com/xuzhuoxi/ExcelExporter 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package basis

const (
    // CodeMMORoomExist 房间不存在
    CodeMMORoomExist int32 = -101
    // CodeMMORoomNotExist 房间已存在
    CodeMMORoomNotExist int32 = -102
    // CodeMMORoomCapLimit 房间容量上限
    CodeMMORoomCapLimit int32 = -103
    // CodeMMOTeamCorpsExist 团队不存在
    CodeMMOTeamCorpsExist int32 = -104
    // CodeMMOTeamCorpsNotExist 团队已存在
    CodeMMOTeamCorpsNotExist int32 = -105
    // CodeMMOTeamCorpsCapLimit 团队容量上限
    CodeMMOTeamCorpsCapLimit int32 = -106
    // CodeMMOTeamExist 队伍不存在
    CodeMMOTeamExist int32 = -107
    // CodeMMOTeamNotExist 队伍已存在
    CodeMMOTeamNotExist int32 = -108
    // CodeMMOTeamCapLimit 队伍容量上限
    CodeMMOTeamCapLimit int32 = -109
    // CodeMMOChanExist 频道不存在
    CodeMMOChanExist int32 = -110
    // CodeMMOChanNotExist 频道已存在
    CodeMMOChanNotExist int32 = -111
    // CodeMMOChanCapLimit 频道容量上限
    CodeMMOChanCapLimit int32 = -112
    // CodeMMOPlayerExist 用户已存在
    CodeMMOPlayerExist int32 = -113
    // CodeMMOPlayerNotExist 用户不存在
    CodeMMOPlayerNotExist int32 = -114
    // CodeMMOUnitExist 单位已存在
    CodeMMOUnitExist int32 = -115
    // CodeMMOUnitNotExist 单位不存在
    CodeMMOUnitNotExist int32 = -116
    // CodeMMOIndexType 索引类型不匹配
    CodeMMOIndexType int32 = -200
    // CodeMMOOther 其它错误
    CodeMMOOther int32 = -201
)