//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by ExcelExporter
//     version 2.0
//     from https://github.com/xuzhuoxi/ExcelExporter 
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package vars

const (
    // UnitOwner 拥有者
    UnitOwner string = "ow"
    // UnitRoom 所有房间Id
    UnitRoom string = "rm"
    // UnitPos int32数组;坐标X、坐标Y、坐标Z
    UnitPos string = "pos"
    // UnitToward 朝向，int16
    UnitToward string = "tw"
    // UnitInputMove int32数组;输入X、输入Y、输入Z
    UnitInputMove string = "im"
    // UnitInputTarget int32数组;目标X、目标Y、目标Z
    UnitInputTarget string = "it"
    // UnitInputJump 输入状态, Jump(bool)
    UnitInputJump string = "ij"
    // UnitActionState 动作状态(uint32)
    UnitActionState string = "as"
)